######################################################################
##
## Filename: decoder_tb.udo
## Created on: Tue Jul 08 2:51:28 PM Pacific Daylight Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
